demosnowdbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DBT_ROLE
      warehouse: DBT_WH
      database: DBT_DEV_DB
      schema: DBT_SCHEMA
    prod:
      type: snowflake
      role: DBT_ROLE
      warehouse: DBT_WH
      database: DBT_PROD_DB
      schema: DBT_SCHEMA
